In [1]:
from viagens_dowload import Viagens # Importa a classe Viagens do módulo viagens_dowload
ano = 2024
vi = Viagens(ano)

In [ ]:
# faz download dos dados de viagens a serviço e carrega os dataframes
viagem_df, trecho_df, passagem_df = vi.pegarViagens()

In [2]:
#se já tiver os csvs baixados, só carrega os dataframes
viagem_df, trecho_df, passagem_df = vi.carregar_csvs()

✅ 2024_Passagem.csv carregado com 400504 linhas (sem cabeçalho).
✅ 2024_Trecho.csv carregado com 1709706 linhas (sem cabeçalho).
✅ 2024_Viagem.csv carregado com 794163 linhas (sem cabeçalho).

In [3]:
%pip install ydata-profiling

Requirement already satisfied: ydata-profiling in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (4.16.1)
Requirement already satisfied: scipy<1.16,>=1.4.1 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (1.13.0)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.1 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (2.3.1)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic>=2 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (2.11.7)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (6.0.2)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (0.8.1)
Requirement already satisfied: numpy<2.2,>=1.16.0 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (1.26.4)
Requirement already satisfied: htmlmin==0.1.12 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (0.1.12)
Requirement already satisfied: phik<0.13,>=0.11.1 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.24.0 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.48.2 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (0.14.5)
Requirement already satisfied: typeguard<5,>=3 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (4.4.4)
Requirement already satisfied: imagehash==4.3.1 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (4.3.1)
Requirement already satisfied: wordcloud>=1.9.3 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (1.9.4)
Requirement already satisfied: dacite>=1.8 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: numba<=0.61,>=0.56.0 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (0.61.0)
Requirement already satisfied: PyWavelets in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from imagehash==4.3.1->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from imagehash==4.3.1->ydata-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from jinja2<3.2,>=2.11.1->ydata-profiling) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.59.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from numba<=0.61,>=0.56.0->ydata-profiling) (0.44.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from phik<0.13,>=0.11.1->ydata-profiling) (1.5.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests<3,>=2.24.0->ydata-profiling) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests<3,>=2.24.0->ydata-profiling) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests<3,>=2.24.0->ydata-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests<3,>=2.24.0->ydata-profiling) (2025.7.14)
Requirement already satisfied: patsy>=0.5.6 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.1)
Requirement already satisfied: colorama in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from tqdm<5,>=4.48.2->ydata-profiling) (0.4.6)
Requirement already satisfied: typing_extensions>=4.14.0 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from typeguard<5,>=3->ydata-profiling) (4.14.1)
Requirement already satisfied: attrs>=19.3.0 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.3.0)
Requirement already satisfied: networkx>=2.4 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.5)
Requirement already satisfied: puremagic in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (1.30)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pydantic>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pydantic>=2->ydata-profiling) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pydantic>=2->ydata-profiling) (0.4.1)
Requirement already satisfied: six>=1.5 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
print("Descrição do DataFrame de trecho:")
trecho_df.describe()

Descrição do DataFrame de trecho:

,Identificador do processo de viagem,Número da Proposta (PCDP),Sequência Trecho,Origem - Data,Origem - País,Origem - UF,Origem - Cidade,Destino - Data,Destino - País,Destino - UF,Destino - Cidade,Meio de transporte,Número Diárias,Missao?
count,1709706,1709706,1709706,1709706,1709706,1675093,1709706,1709706,1709706,1675276,1709706,1709706,1709706,1709706
unique,675726,107444,72,464,178,28,6481,470,179,28,6479,8,401,2
top,0000000000019617576,Sem informaçã,1,29/11/2024,Brasil,São Paulo,Brasília,29/11/2024,Brasil,São Paulo,Brasília,Veículo Oficial,"0,50",Não
freq,72,2085,675726,10635,1675072,184659,175013,17116,1675255,185369,176307,850422,579120,863779

In [3]:
print("head do DataFrame de trecho:")
trecho_df.head()

head do DataFrame de trecho:

,Identificador do processo de viagem,Número da Proposta (PCDP),Sequência Trecho,Origem - Data,Origem - País,Origem - UF,Origem - Cidade,Destino - Data,Destino - País,Destino - UF,Destino - Cidade,Meio de transporte,Número Diárias,Missao?
0,0000000000018831091,000011/24,2,25/02/2024,Brasil,Acre,Rio Branco,25/02/2024,Brasil,Acre,Xapuri,Veículo Próprio,"0,50",Não
1,0000000000018831091,000011/24,1,23/02/2024,Brasil,Acre,Xapuri,25/02/2024,Brasil,Acre,Rio Branco,Veículo Próprio,"2,00",Sim
2,0000000000018831495,000001/24,2,22/01/2024,Brasil,São Paulo,São Paulo,22/01/2024,Brasil,Minas Gerais,Uberlândia,Aéreo,"0,00",Não
3,0000000000018831495,000001/24,1,18/01/2024,Brasil,Minas Gerais,Uberlândia,22/01/2024,Brasil,São Paulo,São Paulo,Aéreo,"0,00",Sim
4,0000000000018831777,000002/24,2,04/03/2024,Brasil,São Paulo,São Paulo,04/03/2024,Brasil,Minas Gerais,Uberlândia,Aéreo,"0,00",Não

In [4]:
passagem_df.describe()

,Identificador do processo de viagem,Número da Proposta (PCDP),Situação,Viagem Urgente,Justificativa Urgência Viagem,Código do órgão superior,Nome do órgão superior,Código órgão solicitante,Nome órgão solicitante,CPF viajante,...,Função,Descrição Função,Período - Data de início,Período - Data de fim,Destinos,Motivo,Valor diárias,Valor passagens,Valor devolução,Valor outros gastos
count,794163,794163,794163,794163,793940,794163,794163,794163,794163,661910,...,794163,794160,794163,794163,794163,794162,794163,794163,794163,794163
unique,794162,107445,2,2,169391,35,35,206,206,156122,...,174,156,366,471,35593,363012,73111,160075,4702,16262
top,0000000000020598362,Informações p,Realizada,SIM,Sem informação,30000,Ministério da Justiça e Segurança Pública,30108,Polícia Federal,***.000.000-**,...,-1,Sem informação,25/11/2024,29/11/2024,Informações protegidas por sigilo,Informação protegida por sigilo nos termos da ...,"0,00","0,00","0,00","0,00"
freq,2,118436,783439,463897,212117,179549,179549,68712,68712,943,...,361705,361705,8333,8591,118436,118436,92080,546520,768521,758572

In [5]:
passagem_df.head()

,Identificador do processo de viagem,Número da Proposta (PCDP),Situação,Viagem Urgente,Justificativa Urgência Viagem,Código do órgão superior,Nome do órgão superior,Código órgão solicitante,Nome órgão solicitante,CPF viajante,...,Função,Descrição Função,Período - Data de início,Período - Data de fim,Destinos,Motivo,Valor diárias,Valor passagens,Valor devolução,Valor outros gastos
0,0000000000018831091,000011/24,Realizada,NÃO,Sem informação,26000,Ministério da Educação,26425,"Instituto Federal de Educação, Ciência e Tecno...",***.405.257-**,...,-1,Sem informação,23/02/2024,25/02/2024,Rio Branco/AC,Ministrar a disciplina de Conceitos e Aplicaçõ...,"929,18","0,00","0,00","0,00"
1,0000000000018831495,000001/24,Realizada,NÃO,Sem informação,26000,Ministério da Educação,26274,Fundação Universidade Federal de Uberlândia,***.587.016-**,...,-1,Sem informação,18/01/2024,22/01/2024,São Paulo/SP,Participação nas atividades do ESTAGIO DE CAPA...,"0,00","0,00","0,00","0,00"
2,0000000000018831777,000002/24,Realizada,NÃO,Sem informação,26000,Ministério da Educação,26274,Fundação Universidade Federal de Uberlândia,***.587.016-**,...,-1,Sem informação,29/02/2024,04/03/2024,São Paulo/SP,Participação nas atividades do ESTAGIO DE CAPA...,"0,00","0,00","0,00","0,00"
3,0000000000018831821,000003/24,Realizada,NÃO,Sem informação,26000,Ministério da Educação,26274,Fundação Universidade Federal de Uberlândia,***.587.016-**,...,-1,Sem informação,11/04/2024,15/04/2024,São Paulo/SP,Participação nas atividades do ESTAGIO DE CAPA...,"0,00","0,00","0,00","0,00"
4,0000000000019177818,000001/24-1C,Realizada,SIM,Inclusão das diárias.,26000,Ministério da Educação,26271,Fundação Universidade de Brasília,***.626.601-**,...,-1,Sem informação,29/01/2024,06/02/2024,"Lille/França, Paris/França",Programação dos eventos que a Professora irá p...,"14176,38","6892,31","0,00","0,00"

In [6]:
viagem_df.describe()

,Identificador do processo de viagem,Número da Proposta (PCDP),Meio de transporte,País - Origem ida,UF - Origem ida,Cidade - Origem ida,País - Destino ida,UF - Destino ida,Cidade - Destino ida,País - Origem volta,UF - Origem volta,Cidade - Origem volta,Pais - Destino volta,UF - Destino volta,Cidade - Destino volta,Valor da passagem,Taxa de serviço,Data da emissão/compra,Hora da emissão/compra
count,400504,400504,400504,400504,388474,400504,400504,386076,400504,400504,396954,400504,400504,399612,400504,400504,400504,398800,400504
unique,221833,56865,4,157,28,1093,162,28,1169,127,28,612,107,28,344,180002,2355,517,1203
top,0000000000019668216,Sem informaçã,Aéreo,Brasil,Distrito Federal,Brasília,Brasil,Distrito Federal,Brasília,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,"0,00","0,00",18/10/2024,00:00
freq,37,1704,393581,388473,112621,112621,386075,113584,113584,367663,367663,367663,367663,367663,367663,923,362189,2490,1745

In [7]:
viagem_df.head()

,Identificador do processo de viagem,Número da Proposta (PCDP),Meio de transporte,País - Origem ida,UF - Origem ida,Cidade - Origem ida,País - Destino ida,UF - Destino ida,Cidade - Destino ida,País - Origem volta,UF - Origem volta,Cidade - Origem volta,Pais - Destino volta,UF - Destino volta,Cidade - Destino volta,Valor da passagem,Taxa de serviço,Data da emissão/compra,Hora da emissão/compra
0,0000000000019177818,000001/24-1C,Aéreo,Brasil,Distrito Federal,Brasília,França,NaN,Paris,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,"6871,34","6,60",19/09/2023,18:53
1,0000000000019177818,000001/24-1C,Aéreo,França,NaN,Paris,Brasil,Distrito Federal,Brasília,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,"7,77","6,60",19/09/2023,18:53
2,0000000000019220977,000001/24-1C,Aéreo,Brasil,Paraná,Curitiba,Portugal,NaN,Porto,Portugal,NaN,Porto,Brasil,Paraná,Curitiba,"8596,69","0,00",31/08/2023,14:49
3,0000000000019255612,000002/24,Aéreo,Alemanha,NaN,Munique,Brasil,Rio de Janeiro,Rio de Janeiro,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,"4625,13","0,00",05/10/2023,17:40
4,0000000000019255728,000001/24,Aéreo,Alemanha,NaN,Munique,Brasil,Rio de Janeiro,Rio de Janeiro,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,"4625,13","0,00",05/10/2023,17:34

Tira todos os Nan(not a number) do dataframe

In [4]:
#filtra para viagens aereas 
aereas =  trecho_df[trecho_df['Meio de transporte'] == 'Aéreo']

In [10]:
aereas.describe()

,Identificador do processo de viagem,Número da Proposta (PCDP),Sequência Trecho,Origem - Data,Origem - País,Origem - UF,Origem - Cidade,Destino - Data,Destino - País,Destino - UF,Destino - Cidade,Meio de transporte,Número Diárias,Missao?
count,551218,551218,551218,551218,551218,525692,551218,551218,551218,525814,551218,551218,551218,551218
unique,275017,74967,45,447,174,28,1984,449,175,28,1993,1,242,2
top,0000000000019668216,Sem informaçã,1,08/11/2024,Brasil,Distrito Federal,Brasília,29/11/2024,Brasil,Distrito Federal,Brasília,Aéreo,"0,50",Não
freq,35,1959,250281,3809,525687,142848,142848,6252,525809,143384,143384,551218,178929,301131

In [11]:
#filtra para remover linhasrepetidas 
aereas = aereas.drop_duplicates(subset=['Origem - Cidade', 'Destino - Cidade'])

In [12]:
aereas.describe()

,Identificador do processo de viagem,Número da Proposta (PCDP),Sequência Trecho,Origem - Data,Origem - País,Origem - UF,Origem - Cidade,Destino - Data,Destino - País,Destino - UF,Destino - Cidade,Meio de transporte,Número Diárias,Missao?
count,18282,18282,18282,18282,18282,12586,18282,18282,18282,12592,18282,18282,18282,18282
unique,10752,6113,33,401,174,28,1984,408,175,28,1993,1,99,2
top,0000000000019928947,000001/24,1,31/01/2024,Brasil,São Paulo,Brasília,31/01/2024,Brasil,São Paulo,Brasília,Aéreo,"0,00",Não
freq,8,64,6809,139,12583,1627,915,163,12589,1632,918,18282,8203,10333

In [ ]:
import  ydata_profiling
from ydata_profiling import ProfileReport

profile = ProfileReport(aereas)
profile.to_notebook_iframe()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 14/14 [00:10<00:00,  1.38it/s]

In [14]:
# 1. Primeiro, verificar os nomes reais das colunas:
print("Colunas de passagem_df:", passagem_df.columns.tolist())
print("Colunas de viagem_df:", viagem_df.columns.tolist())

Colunas de passagem_df: ['Identificador do processo de viagem', 'Número da Proposta (PCDP)', 'Situação', 'Viagem Urgente', 'Justificativa Urgência Viagem', 'Código do órgão superior', 'Nome do órgão superior', 'Código órgão solicitante', 'Nome órgão solicitante', 'CPF viajante', 'Nome', 'Cargo', 'Função', 'Descrição Função', 'Período - Data de início', 'Período - Data de fim', 'Destinos', 'Motivo', 'Valor diárias', 'Valor passagens', 'Valor devolução', 'Valor outros gastos']
Colunas de viagem_df: ['Identificador do processo de viagem', 'Número da Proposta (PCDP)', 'Meio de transporte', 'País - Origem ida', 'UF - Origem ida', 'Cidade - Origem ida', 'País - Destino ida', 'UF - Destino ida', 'Cidade - Destino ida', 'País - Origem volta', 'UF - Origem volta', 'Cidade - Origem volta', 'Pais - Destino volta', 'UF - Destino volta', 'Cidade - Destino volta', 'Valor da passagem', 'Taxa de serviço', 'Data da emissão/compra', 'Hora da emissão/compra']

In [15]:
import pandas as pd

# 2. Filtrar apenas as passagens com situação "Realizada"
passagens_realizadas = passagem_df[passagem_df['Situação'] == 'Realizada']

# 3. Realizar o join com viagem_df com base no 'Identificador do processo de viagem'
# Utilizando inner join para pegar apenas os IDs em comum
aereas_realizadas = pd.merge(passagens_realizadas, viagem_df, on='Identificador do processo de viagem', how='inner')

# 4. Resultado
print(f"✅ Total de registros após o join: {len(aereas_realizadas)}")

✅ Total de registros após o join: 383684

In [16]:
aereas_realizadas.describe()

,Identificador do processo de viagem,Número da Proposta (PCDP)_x,Situação,Viagem Urgente,Justificativa Urgência Viagem,Código do órgão superior,Nome do órgão superior,Código órgão solicitante,Nome órgão solicitante,CPF viajante,...,País - Origem volta,UF - Origem volta,Cidade - Origem volta,Pais - Destino volta,UF - Destino volta,Cidade - Destino volta,Valor da passagem,Taxa de serviço,Data da emissão/compra,Hora da emissão/compra
count,383684,383684,383684,383684,383567,383684,383684,383684,383684,307837,...,383684,380250,383684,383684,382809,383684,383684,383684,382035,383684
unique,212656,56024,1,2,56395,35,35,204,204,64922,...,126,28,604,107,28,340,175354,2263,513,1200
top,0000000000019668216,Sem informaçã,Realizada,SIM,Sem informação,52000,Ministério da Defesa,52121,Comando do Exército,***.000.000-**,...,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,"0,00","0,00",18/10/2024,00:00
freq,37,1649,383684,224148,159536,83360,83360,30748,30748,893,...,352484,352484,352484,352484,352484,352484,860,346452,2425,1689

In [17]:
aereas_realizadas.head()

,Identificador do processo de viagem,Número da Proposta (PCDP)_x,Situação,Viagem Urgente,Justificativa Urgência Viagem,Código do órgão superior,Nome do órgão superior,Código órgão solicitante,Nome órgão solicitante,CPF viajante,...,País - Origem volta,UF - Origem volta,Cidade - Origem volta,Pais - Destino volta,UF - Destino volta,Cidade - Destino volta,Valor da passagem,Taxa de serviço,Data da emissão/compra,Hora da emissão/compra
0,0000000000019177818,000001/24-1C,Realizada,SIM,Inclusão das diárias.,26000,Ministério da Educação,26271,Fundação Universidade de Brasília,***.626.601-**,...,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,"6871,34","6,60",19/09/2023,18:53
1,0000000000019177818,000001/24-1C,Realizada,SIM,Inclusão das diárias.,26000,Ministério da Educação,26271,Fundação Universidade de Brasília,***.626.601-**,...,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,"7,77","6,60",19/09/2023,18:53
2,0000000000019220977,000001/24-1C,Realizada,NÃO,Sem informação,26000,Ministério da Educação,26258,Universidade Tecnológica Federal do Paraná,***.133.960-**,...,Portugal,NaN,Porto,Brasil,Paraná,Curitiba,"8596,69","0,00",31/08/2023,14:49
3,0000000000019255612,000002/24,Realizada,NÃO,Sem informação,52000,Ministério da Defesa,52121,Comando do Exército,***.480.087-**,...,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,"4625,13","0,00",05/10/2023,17:40
4,0000000000019255728,000001/24,Realizada,NÃO,Sem informação,52000,Ministério da Defesa,52121,Comando do Exército,NaN,...,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,"4625,13","0,00",05/10/2023,17:34

In [42]:
# Garante que os nomes das colunas não tenham espaços extras
trecho_df.columns = trecho_df.columns.str.strip()
aereas_realizadas.columns = aereas_realizadas.columns.str.strip()

# pega o dataframe trecho_df e filtra pelos identificadores de viagem que estão em aereas_realizadas
aereas_filtradas = trecho_df[trecho_df['Identificador do processo de viagem'].isin(aereas_realizadas['Identificador do processo de viagem'])]

In [43]:
aereas_filtradas.describe()

,Identificador do processo de viagem,Número da Proposta (PCDP),Sequência Trecho,Origem - Data,Origem - País,Origem - UF,Origem - Cidade,Destino - Data,Destino - País,Destino - UF,Destino - Cidade,Meio de transporte,Número Diárias,Missao?
count,534650,534650,534650,534650,534650,515472,534650,534650,534650,515677,534650,534650,534650,534650
unique,212102,55924,57,417,165,28,3417,425,166,28,3417,8,298,2
top,0000000000019673146,Sem informaçã,1,08/11/2024,Brasil,Distrito Federal,Brasília,29/11/2024,Brasil,Distrito Federal,Brasília,Aéreo,"0,00",Não
freq,57,1717,212102,3641,515462,121971,121971,6051,515667,122934,122934,406147,169737,288231

In [44]:
aereas_realizadas.head()

,Identificador do processo de viagem,Número da Proposta (PCDP)_x,Situação,Viagem Urgente,Justificativa Urgência Viagem,Código do órgão superior,Nome do órgão superior,Código órgão solicitante,Nome órgão solicitante,CPF viajante,...,País - Origem volta,UF - Origem volta,Cidade - Origem volta,Pais - Destino volta,UF - Destino volta,Cidade - Destino volta,Valor da passagem,Taxa de serviço,Data da emissão/compra,Hora da emissão/compra
0,0000000000019177818,000001/24-1C,Realizada,SIM,Inclusão das diárias.,26000,Ministério da Educação,26271,Fundação Universidade de Brasília,***.626.601-**,...,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,"6871,34","6,60",19/09/2023,18:53
1,0000000000019177818,000001/24-1C,Realizada,SIM,Inclusão das diárias.,26000,Ministério da Educação,26271,Fundação Universidade de Brasília,***.626.601-**,...,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,"7,77","6,60",19/09/2023,18:53
2,0000000000019220977,000001/24-1C,Realizada,NÃO,Sem informação,26000,Ministério da Educação,26258,Universidade Tecnológica Federal do Paraná,***.133.960-**,...,Portugal,NaN,Porto,Brasil,Paraná,Curitiba,"8596,69","0,00",31/08/2023,14:49
3,0000000000019255612,000002/24,Realizada,NÃO,Sem informação,52000,Ministério da Defesa,52121,Comando do Exército,***.480.087-**,...,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,"4625,13","0,00",05/10/2023,17:40
4,0000000000019255728,000001/24,Realizada,NÃO,Sem informação,52000,Ministério da Defesa,52121,Comando do Exército,NaN,...,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,"4625,13","0,00",05/10/2023,17:34

In [22]:
pip install ydata-profiling

Requirement already satisfied: ydata-profiling in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (4.16.1)
Requirement already satisfied: scipy<1.16,>=1.4.1 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (1.13.0)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.1 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (2.3.1)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic>=2 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (2.11.7)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (6.0.2)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (0.8.1)
Requirement already satisfied: numpy<2.2,>=1.16.0 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (1.26.4)
Requirement already satisfied: htmlmin==0.1.12 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (0.1.12)
Requirement already satisfied: phik<0.13,>=0.11.1 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.24.0 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.48.2 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (0.14.5)
Requirement already satisfied: typeguard<5,>=3 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (4.4.4)
Requirement already satisfied: imagehash==4.3.1 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (4.3.1)
Requirement already satisfied: wordcloud>=1.9.3 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (1.9.4)
Requirement already satisfied: dacite>=1.8 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: numba<=0.61,>=0.56.0 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ydata-profiling) (0.61.0)
Requirement already satisfied: PyWavelets in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from imagehash==4.3.1->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from imagehash==4.3.1->ydata-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from jinja2<3.2,>=2.11.1->ydata-profiling) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.59.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from numba<=0.61,>=0.56.0->ydata-profiling) (0.44.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from phik<0.13,>=0.11.1->ydata-profiling) (1.5.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests<3,>=2.24.0->ydata-profiling) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests<3,>=2.24.0->ydata-profiling) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests<3,>=2.24.0->ydata-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests<3,>=2.24.0->ydata-profiling) (2025.7.14)
Requirement already satisfied: patsy>=0.5.6 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.1)
Requirement already satisfied: colorama in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from tqdm<5,>=4.48.2->ydata-profiling) (0.4.6)
Requirement already satisfied: typing_extensions>=4.14.0 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from typeguard<5,>=3->ydata-profiling) (4.14.1)
Requirement already satisfied: attrs>=19.3.0 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.3.0)
Requirement already satisfied: networkx>=2.4 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.5)
Requirement already satisfied: puremagic in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (1.30)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pydantic>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pydantic>=2->ydata-profiling) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pydantic>=2->ydata-profiling) (0.4.1)
Requirement already satisfied: six>=1.5 in c:\users\augusto\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import  ydata_profiling
from ydata_profiling import ProfileReport

profile = ProfileReport(aereas_realizadas)
profile.to_notebook_iframe()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 40/40 [00:32<00:00,  1.22it/s]

In [18]:
origens = aereas['Origem - Cidade']
destinos = aereas['Destino - Cidade']
#converter para dataframe
origens = pd.DataFrame(origens)
destinos = pd.DataFrame(destinos)
origens.describe()

       Origem - Cidade
count           551218
unique            1984
top           Brasília
freq            142848

In [19]:
destinos.describe()

       Destino - Cidade
count            551218
unique             1993
top            Brasília
freq             143384

In [23]:
destinos.head()

   Destino - Cidade
2        Uberlândia
3         São Paulo
8          Brasília
9             Lille
10            Paris

In [ ]:
origens.dropna(inplace=True)
destinos.dropna(inplace=True)
print(origens)
print(destinos)

         Origem - Cidade
2              São Paulo
3             Uberlândia
52         Foz do Iguaçu
66             São Paulo
69              Brasília
...                  ...
1702085  Nova Petrópolis
1702986         Brasília
1702987         Inválido
1703374        São Paulo
1703375         Inválido

[9434 rows x 1 columns]
        Destino - Cidade
2             Uberlândia
3              São Paulo
52              Brasília
66              Brasília
69             São Paulo
...                  ...
1702085     Porto Alegre
1702986         Inválido
1702987         Brasília
1703374         Inválido
1703375        São Paulo

[9434 rows x 1 columns]

In [21]:
from distanciaCidades import Distancia

# for origem, destino in zip(origens, destinos):
#    resultado = calcular_distancia.calcular(origem, destino)
# i = 0

resultados = []
calcular_distancia = Distancia()
for i in range(10):
    origem_cidade = origens.iloc[i]['Origem - Cidade']
    destino_cidade = destinos.iloc[i]['Destino - Cidade']
    resultado = calcular_distancia.calcular(origem_cidade, destino_cidade)
    resultados.append(resultado)
print(resultados)

Erro ao buscar Uberlândia: ('Connection aborted.', ConnectionAbortedError(10053, 'Uma conexão estabelecida foi anulada pelo software no computador host', None, 10053, None))
[None, {'origem': {'latitude': -18.9188041, 'longitude': -48.2767837, 'nome': 'Uberlândia'}, 'destino': {'latitude': -23.5506507, 'longitude': -46.6333824, 'nome': 'São Paulo'}, 'distancia_km': 542.4512288291022, 'mapa_url': 'https://www.google.com/maps/dir/-18.9188041,-48.2767837/-23.5506507,-46.6333824'}, {'origem': {'latitude': -23.5506507, 'longitude': -46.6333824, 'nome': 'São Paulo'}, 'destino': {'latitude': -18.9188041, 'longitude': -48.2767837, 'nome': 'Uberlândia'}, 'distancia_km': 542.4512288291022, 'mapa_url': 'https://www.google.com/maps/dir/-23.5506507,-46.6333824/-18.9188041,-48.2767837'}, {'origem': {'latitude': -18.9188041, 'longitude': -48.2767837, 'nome': 'Uberlândia'}, 'destino': {'latitude': -23.5506507, 'longitude': -46.6333824, 'nome': 'São Paulo'}, 'distancia_km': 542.4512288291022, 'mapa_url': 'https://www.google.com/maps/dir/-18.9188041,-48.2767837/-23.5506507,-46.6333824'}, {'origem': {'latitude': -23.5506507, 'longitude': -46.6333824, 'nome': 'São Paulo'}, 'destino': {'latitude': -18.9188041, 'longitude': -48.2767837, 'nome': 'Uberlândia'}, 'distancia_km': 542.4512288291022, 'mapa_url': 'https://www.google.com/maps/dir/-23.5506507,-46.6333824/-18.9188041,-48.2767837'}, {'origem': {'latitude': -18.9188041, 'longitude': -48.2767837, 'nome': 'Uberlândia'}, 'destino': {'latitude': -23.5506507, 'longitude': -46.6333824, 'nome': 'São Paulo'}, 'distancia_km': 542.4512288291022, 'mapa_url': 'https://www.google.com/maps/dir/-18.9188041,-48.2767837/-23.5506507,-46.6333824'}, {'origem': {'latitude': 48.8534951, 'longitude': 2.3483915, 'nome': 'Paris'}, 'destino': {'latitude': -10.3333333, 'longitude': -53.2, 'nome': 'Brasil'}, 'distancia_km': 8521.656409036166, 'mapa_url': 'https://www.google.com/maps/dir/48.8534951,2.3483915/-10.3333333,-53.2'}, {'origem': {'latitude': 48.8534951, 'longitude': 2.3483915, 'nome': 'Paris'}, 'destino': {'latitude': 50.6365654, 'longitude': 3.0635282, 'nome': 'Lille'}, 'distancia_km': 204.81605515200658, 'mapa_url': 'https://www.google.com/maps/dir/48.8534951,2.3483915/50.6365654,3.0635282'}, {'origem': {'latitude': 50.6365654, 'longitude': 3.0635282, 'nome': 'Lille'}, 'destino': {'latitude': 48.8534951, 'longitude': 2.3483915, 'nome': 'Paris'}, 'distancia_km': 204.81605515200658, 'mapa_url': 'https://www.google.com/maps/dir/50.6365654,3.0635282/48.8534951,2.3483915'}, {'origem': {'latitude': -10.3333333, 'longitude': -53.2, 'nome': 'Brasil'}, 'destino': {'latitude': 48.8534951, 'longitude': 2.3483915, 'nome': 'Paris'}, 'distancia_km': 8521.656409036166, 'mapa_url': 'https://www.google.com/maps/dir/-10.3333333,-53.2/48.8534951,2.3483915'}]

In [ ]:
import pandas as pd
from distanciaCidades import Distancia

# Inicializa a classe
calcular_distancia = Distancia()

# Lista para armazenar resultados estruturados
dados = []

# Itera pelas 10 primeiras linhas (ou até onde houver dados)
for i in range(min(10, len(origens), len(destinos))):
    origem_cidade = origens.iloc[i]['Origem - Cidade']
    destino_cidade = destinos.iloc[i]['Destino - Cidade']
    
    resultado = calcular_distancia.calcular(origem_cidade, destino_cidade)
    
    if resultado:
        dados.append({
            'id': i,
            'origem': resultado['origem']['nome'],
            'destino': resultado['destino']['nome'],
            'distancia': round(resultado['distancia_km'], 2)
        })
    else:
        dados.append({
            'id': i,
            'origem': origem_cidade,
            'destino': destino_cidade,
            'distancia': None
        })

# Criação do DataFrame final
df_distancia = pd.DataFrame(dados)

# Exibe resultado
print(df_distancia)

   id      origem     destino  distancia
0   0  Rio Branco      Xapuri     105.62
1   1      Xapuri  Rio Branco     105.62
2   2   São Paulo  Uberlândia     542.45
3   3  Uberlândia   São Paulo     542.45
4   4   São Paulo  Uberlândia     542.45
5   5  Uberlândia   São Paulo     542.45
6   6   São Paulo  Uberlândia     542.45
7   7  Uberlândia   São Paulo     542.45
8   8       Paris      Brasil    8520.26
9   9       Paris       Lille     204.76

In [ ]:
# resultado = pd.DataFrame(resultado, columns=['Origem', 'Destino', 'Distância'])
# df_distancia.describe()
print(df_distancia)

   id      origem     destino  distancia
0   0  Rio Branco      Xapuri     105.62
1   1      Xapuri  Rio Branco     105.62
2   2   São Paulo  Uberlândia     542.45
3   3  Uberlândia   São Paulo     542.45
4   4   São Paulo  Uberlândia     542.45
5   5  Uberlândia   São Paulo     542.45
6   6   São Paulo  Uberlândia     542.45
7   7  Uberlândia   São Paulo     542.45
8   8       Paris      Brasil    8520.26
9   9       Paris       Lille     204.76

In [ ]:
from pprint import pprint

pprint(resultado)
# Exibe as primeiras linhas do DataFrame de origens e destinos
print(origens.head())
print(destinos.head())

{'destino': {'latitude': 59.9606739,
             'longitude': 30.1586551,
             'nome': 'Санкт-Петербург'},
 'distancia_km': 10634.983626241788,
 'mapa_url': 'https://www.google.com/maps/dir/-10.3333333,-53.2/59.9606739,30.1586551',
 'origem': {'latitude': -10.3333333, 'longitude': -53.2, 'nome': 'Brasil'}}
  Origem - Cidade
0      Rio Branco
1          Xapuri
2       São Paulo
3      Uberlândia
4       São Paulo
  Destino - Cidade
0           Xapuri
1       Rio Branco
2       Uberlândia
3        São Paulo
4       Uberlândia