In [1]:
from viagens_dowload import Viagens # Importa a classe Viagens do módulo viagens_dowload
ano = 2024
vi = Viagens(ano)
viagem_df, trecho_df, passagem_df = vi.pegarViagens()

🔄 Fazendo download de: https://portaldatransparencia.gov.br/download-de-dados/viagens/2024
➡️ Redirecionado para o CSV: https://dadosabertos-download.cgu.gov.br/PortalDaTransparencia/saida/viagens/2024_20250720_Viagens.zip
✅ CSV salvo em: dadosViagens/viagens_2024.zip
✅ Arquivos extraídos para: d:\projetoExtensao\dadosViagens\dados_viagens2024
📁 Conteúdo extraído:
 - 2024_Pagamento.csv
 - 2024_Passagem.csv
 - 2024_Trecho.csv
 - 2024_Viagem.csv
✅ Arquivo ZIP removido: dadosViagens/viagens_2024.zip
✅ Arquivo de pagamentos removido: dadosViagens/dados_viagens2024/2024_Pagamento.csv
✅ 2024_Passagem.csv carregado com 399520 linhas (sem cabeçalho).
✅ 2024_Trecho.csv carregado com 1704586 linhas (sem cabeçalho).
✅ 2024_Viagem.csv carregado com 791910 linhas (sem cabeçalho).

In [5]:
trecho_df.describe()

,Identificador do processo de viagem,Número da Proposta (PCDP),Sequência Trecho,Origem - Data,Origem - País,Origem - UF,Origem - Cidade,Destino - Data,Destino - País,Destino - UF,Destino - Cidade,Meio de transporte,Número Diárias,Missao?
count,1704586,1704586,1704586,1704586,1704586,1670167,1704586,1704586,1704586,1670354,1704586,1704586,1704586,1704586
unique,673596,107261,72,449,177,28,6478,454,178,28,6476,8,400,2
top,0000000000019617576,Sem informaçã,1,25/11/2024,Brasil,São Paulo,Brasília,29/11/2024,Brasil,São Paulo,Brasília,Veículo Oficial,"0,50",Não
freq,72,2083,673596,10572,1670146,184057,174599,17010,1670333,184773,175889,848445,577454,861168

In [4]:
trecho_df.head()

,Identificador do processo de viagem,Número da Proposta (PCDP),Sequência Trecho,Origem - Data,Origem - País,Origem - UF,Origem - Cidade,Destino - Data,Destino - País,Destino - UF,Destino - Cidade,Meio de transporte,Número Diárias,Missao?
0,0000000000018831091,000011/24,2,25/02/2024,Brasil,Acre,Rio Branco,25/02/2024,Brasil,Acre,Xapuri,Veículo Próprio,"0,50",Não
1,0000000000018831091,000011/24,1,23/02/2024,Brasil,Acre,Xapuri,25/02/2024,Brasil,Acre,Rio Branco,Veículo Próprio,"2,00",Sim
2,0000000000018831495,000001/24,2,22/01/2024,Brasil,São Paulo,São Paulo,22/01/2024,Brasil,Minas Gerais,Uberlândia,Aéreo,"0,00",Não
3,0000000000018831495,000001/24,1,18/01/2024,Brasil,Minas Gerais,Uberlândia,22/01/2024,Brasil,São Paulo,São Paulo,Aéreo,"0,00",Sim
4,0000000000018831777,000002/24,2,04/03/2024,Brasil,São Paulo,São Paulo,04/03/2024,Brasil,Minas Gerais,Uberlândia,Aéreo,"0,00",Não

In [6]:
passagem_df.describe()

,Identificador do processo de viagem,Número da Proposta (PCDP),Situação,Viagem Urgente,Justificativa Urgência Viagem,Código do órgão superior,Nome do órgão superior,Código órgão solicitante,Nome órgão solicitante,CPF viajante,...,Função,Descrição Função,Período - Data de início,Período - Data de fim,Destinos,Motivo,Valor diárias,Valor passagens,Valor devolução,Valor outros gastos
count,791910,791910,791910,791910,791687,791910,791910,791910,791910,660581,...,791910,791907,791910,791910,791910,791909,791910,791910,791910,791910
unique,791909,107262,2,2,168883,27,26,175,175,155733,...,174,156,366,459,35535,361904,72909,159766,4680,16254
top,0000000000020598362,Informações p,Realizada,SIM,Sem informação,26000,Ministério da Educação,-1,Sem informação,***.000.000-**,...,-1,Sem informação,25/11/2024,29/11/2024,Informações protegidas por sigilo,Informação protegida por sigilo nos termos da ...,"0,00","0,00","0,00","0,00"
freq,2,118313,781211,462273,211611,160391,160391,150692,150692,937,...,360755,360755,8295,8543,118313,118313,91696,544876,766349,756345

In [7]:
viagem_df.describe()

,Identificador do processo de viagem,Número da Proposta (PCDP),Meio de transporte,País - Origem ida,UF - Origem ida,Cidade - Origem ida,País - Destino ida,UF - Destino ida,Cidade - Destino ida,País - Origem volta,UF - Origem volta,Cidade - Origem volta,Pais - Destino volta,UF - Destino volta,Cidade - Destino volta,Valor da passagem,Taxa de serviço,Data da emissão/compra,Hora da emissão/compra
count,399520,399520,399520,399520,387523,399520,399520,385132,399520,399520,395979,399520,399520,398635,399520,399520,399520,397818,399520
unique,221256,56761,4,156,28,1090,161,28,1166,127,28,610,107,28,343,179682,2346,506,1202
top,0000000000019668216,Sem informaçã,Aéreo,Brasil,Distrito Federal,Brasília,Brasil,Distrito Federal,Brasília,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,"0,00","0,00",18/10/2024,00:00
freq,37,1702,392717,387522,112457,112457,385131,113398,113398,366811,366811,366811,366811,366811,366811,919,361347,2473,1743

Tira todos os Nan(not a number) do dataframe

In [8]:
passagem_df.dropna()

,Identificador do processo de viagem,Número da Proposta (PCDP),Situação,Viagem Urgente,Justificativa Urgência Viagem,Código do órgão superior,Nome do órgão superior,Código órgão solicitante,Nome órgão solicitante,CPF viajante,...,Função,Descrição Função,Período - Data de início,Período - Data de fim,Destinos,Motivo,Valor diárias,Valor passagens,Valor devolução,Valor outros gastos
0,0000000000018831091,000011/24,Realizada,NÃO,Sem informação,26000,Ministério da Educação,26425,"Instituto Federal de Educação, Ciência e Tecno...",***.405.257-**,...,-1,Sem informação,23/02/2024,25/02/2024,Rio Branco/AC,Ministrar a disciplina de Conceitos e Aplicaçõ...,"929,18","0,00","0,00","0,00"
1,0000000000018831495,000001/24,Realizada,NÃO,Sem informação,26000,Ministério da Educação,26274,Fundação Universidade Federal de Uberlândia,***.587.016-**,...,-1,Sem informação,18/01/2024,22/01/2024,São Paulo/SP,Participação nas atividades do ESTAGIO DE CAPA...,"0,00","0,00","0,00","0,00"
2,0000000000018831777,000002/24,Realizada,NÃO,Sem informação,26000,Ministério da Educação,26274,Fundação Universidade Federal de Uberlândia,***.587.016-**,...,-1,Sem informação,29/02/2024,04/03/2024,São Paulo/SP,Participação nas atividades do ESTAGIO DE CAPA...,"0,00","0,00","0,00","0,00"
3,0000000000018831821,000003/24,Realizada,NÃO,Sem informação,26000,Ministério da Educação,26274,Fundação Universidade Federal de Uberlândia,***.587.016-**,...,-1,Sem informação,11/04/2024,15/04/2024,São Paulo/SP,Participação nas atividades do ESTAGIO DE CAPA...,"0,00","0,00","0,00","0,00"
4,0000000000019177818,000001/24-1C,Realizada,SIM,Inclusão das diárias.,26000,Ministério da Educação,26271,Fundação Universidade de Brasília,***.626.601-**,...,-1,Sem informação,29/01/2024,06/02/2024,"Lille/França, Paris/França",Programação dos eventos que a Professora irá p...,"14176,38","6892,31","0,00","0,00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
791904,0000000002024001906,Sem informaçã,Realizada,NÃO,Sem informação,-1,Sem informação,-1,Sem informação,***.759.868-**,...,-1,Sem informação,18/12/2024,19/12/2024,Sem informação,Cumprir agenda de trabalho em Brasília.,"1109,09","3180,06","0,00","0,00"
791905,0000000002024001911,Sem informaçã,Realizada,NÃO,Sem informação,-1,Sem informação,-1,Sem informação,***.902.438-**,...,-1,Sem informação,16/12/2024,16/12/2024,Sem informação,"Participar, como palestrante, no evento '1 ano...","262,05","0,00","0,00","0,00"
791906,0000000002024001912,Sem informaçã,Realizada,NÃO,Sem informação,-1,Sem informação,-1,Sem informação,***.697.505-**,...,-1,Sem informação,17/12/2024,18/12/2024,Sem informação,Assessorar o Diretor de Fiscalização e cumprir...,"1204,09","4044,69","0,00","0,00"
791907,0000000002024001938,Sem informaçã,Não realizada,NÃO,Sem informação,-1,Sem informação,-1,Sem informação,***.827.438-**,...,-1,Sem informação,26/12/2024,27/12/2024,Sem informação,Cumprir agenda em Brasília.,"0,00","0,00","0,00","0,00"
791908,0000000002024001946,Sem informaçã,Realizada,NÃO,Sem informação,-1,Sem informação,-1,Sem informação,***.425.230-**,...,-1,Sem informação,29/12/2024,31/12/2024,Sem informação,Suspensão das férias do servidor por motivo de...,"0,00","5562,82","0,00","0,00"

In [24]:
#filtra para viagens aereas 
aereas =  trecho_df[trecho_df['Meio de transporte'] == 'Aéreo']

In [25]:
aereas.describe()

,Identificador do processo de viagem,Número da Proposta (PCDP),Sequência Trecho,Origem - Data,Origem - País,Origem - UF,Origem - Cidade,Destino - Data,Destino - País,Destino - UF,Destino - Cidade,Meio de transporte,Número Diárias,Missao?
count,549159,549159,549159,549159,549159,523771,549159,549159,549159,523897,549159,549159,549159,549159
unique,274019,74612,45,436,173,28,1978,441,174,28,1986,1,242,2
top,0000000000019668216,Sem informaçã,1,08/11/2024,Brasil,Distrito Federal,Brasília,29/11/2024,Brasil,Distrito Federal,Brasília,Aéreo,"0,50",Não
freq,35,1957,249380,3779,523766,142480,142480,6193,523892,143009,143009,549159,178322,300017

In [26]:
#filtra para remover linhasrepetidas 
aereas = aereas.drop_duplicates(subset=['Origem - Cidade', 'Destino - Cidade'])

In [27]:
aereas.describe()

,Identificador do processo de viagem,Número da Proposta (PCDP),Sequência Trecho,Origem - Data,Origem - País,Origem - UF,Origem - Cidade,Destino - Data,Destino - País,Destino - UF,Destino - Cidade,Meio de transporte,Número Diárias,Missao?
count,18190,18190,18190,18190,18190,12536,18190,18190,18190,12544,18190,18190,18190,18190
unique,10701,6087,33,392,173,28,1978,399,174,28,1986,1,99,2
top,0000000000019928947,000001/24,1,31/01/2024,Brasil,São Paulo,Brasília,31/01/2024,Brasil,São Paulo,Brasília,Aéreo,"0,00",Não
freq,8,64,6773,139,12533,1620,914,163,12541,1626,917,18190,8140,10284

In [28]:
viagem_df.describe()

,Identificador do processo de viagem,Número da Proposta (PCDP),Meio de transporte,País - Origem ida,UF - Origem ida,Cidade - Origem ida,País - Destino ida,UF - Destino ida,Cidade - Destino ida,País - Origem volta,UF - Origem volta,Cidade - Origem volta,Pais - Destino volta,UF - Destino volta,Cidade - Destino volta,Valor da passagem,Taxa de serviço,Data da emissão/compra,Hora da emissão/compra
count,399520,399520,399520,399520,387523,399520,399520,385132,399520,399520,395979,399520,399520,398635,399520,399520,399520,397818,399520
unique,221256,56761,4,156,28,1090,161,28,1166,127,28,610,107,28,343,179682,2346,506,1202
top,0000000000019668216,Sem informaçã,Aéreo,Brasil,Distrito Federal,Brasília,Brasil,Distrito Federal,Brasília,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,"0,00","0,00",18/10/2024,00:00
freq,37,1702,392717,387522,112457,112457,385131,113398,113398,366811,366811,366811,366811,366811,366811,919,361347,2473,1743

In [29]:
# 1. Primeiro, verificar os nomes reais das colunas:
print("Colunas de passagem_df:", passagem_df.columns.tolist())
print("Colunas de viagem_df:", viagem_df.columns.tolist())

Colunas de passagem_df: ['Identificador do processo de viagem', 'Número da Proposta (PCDP)', 'Situação', 'Viagem Urgente', 'Justificativa Urgência Viagem', 'Código do órgão superior', 'Nome do órgão superior', 'Código órgão solicitante', 'Nome órgão solicitante', 'CPF viajante', 'Nome', 'Cargo', 'Função', 'Descrição Função', 'Período - Data de início', 'Período - Data de fim', 'Destinos', 'Motivo', 'Valor diárias', 'Valor passagens', 'Valor devolução', 'Valor outros gastos']
Colunas de viagem_df: ['Identificador do processo de viagem', 'Número da Proposta (PCDP)', 'Meio de transporte', 'País - Origem ida', 'UF - Origem ida', 'Cidade - Origem ida', 'País - Destino ida', 'UF - Destino ida', 'Cidade - Destino ida', 'País - Origem volta', 'UF - Origem volta', 'Cidade - Origem volta', 'Pais - Destino volta', 'UF - Destino volta', 'Cidade - Destino volta', 'Valor da passagem', 'Taxa de serviço', 'Data da emissão/compra', 'Hora da emissão/compra']

In [31]:
# 2. Filtrar apenas as passagens com situação "Realizada"
passagens_realizadas = passagem_df[passagem_df['Situação'] == 'Realizada']

# 3. Realizar o join com viagem_df com base no 'Identificador do processo de viagem'
# Utilizando inner join para pegar apenas os IDs em comum
aereas_realizadas = pd.merge(passagens_realizadas, viagem_df, on='Identificador do processo de viagem', how='inner')

# 4. Resultado
print(f"✅ Total de registros após o join: {len(aereas_realizadas)}")

✅ Total de registros após o join: 382742

In [34]:
aereas_realizadas.describe()

,Identificador do processo de viagem,Número da Proposta (PCDP)_x,Situação,Viagem Urgente,Justificativa Urgência Viagem,Código do órgão superior,Nome do órgão superior,Código órgão solicitante,Nome órgão solicitante,CPF viajante,...,País - Origem volta,UF - Origem volta,Cidade - Origem volta,Pais - Destino volta,UF - Destino volta,Cidade - Destino volta,Valor da passagem,Taxa de serviço,Data da emissão/compra,Hora da emissão/compra
count,382742,382742,382742,382742,382625,382742,382742,382742,382742,307329,...,382742,379317,382742,382742,381874,382742,382742,382742,381095,382742
unique,212102,55924,1,2,56247,27,26,173,173,64765,...,126,28,602,107,28,340,175036,2254,502,1199
top,0000000000019668216,Sem informaçã,Realizada,SIM,Sem informação,-1,Sem informação,-1,Sem informação,***.000.000-**,...,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,"0,00","0,00",18/10/2024,00:00
freq,37,1647,382742,223510,159232,95190,95190,95190,95190,891,...,351666,351666,351666,351666,351666,351666,856,345644,2408,1687

In [40]:
aereas_realizadas.head()

,Identificador do processo de viagem,Número da Proposta (PCDP)_x,Situação,Viagem Urgente,Justificativa Urgência Viagem,Código do órgão superior,Nome do órgão superior,Código órgão solicitante,Nome órgão solicitante,CPF viajante,...,País - Origem volta,UF - Origem volta,Cidade - Origem volta,Pais - Destino volta,UF - Destino volta,Cidade - Destino volta,Valor da passagem,Taxa de serviço,Data da emissão/compra,Hora da emissão/compra
0,0000000000019177818,000001/24-1C,Realizada,SIM,Inclusão das diárias.,26000,Ministério da Educação,26271,Fundação Universidade de Brasília,***.626.601-**,...,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,"6871,34","6,60",19/09/2023,18:53
1,0000000000019177818,000001/24-1C,Realizada,SIM,Inclusão das diárias.,26000,Ministério da Educação,26271,Fundação Universidade de Brasília,***.626.601-**,...,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,"7,77","6,60",19/09/2023,18:53
2,0000000000019220977,000001/24-1C,Realizada,NÃO,Sem informação,26000,Ministério da Educação,26258,Universidade Tecnológica Federal do Paraná,***.133.960-**,...,Portugal,NaN,Porto,Brasil,Paraná,Curitiba,"8596,69","0,00",31/08/2023,14:49
3,0000000000019255612,000002/24,Realizada,NÃO,Sem informação,52000,Ministério da Defesa,52121,Comando do Exército,***.480.087-**,...,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,"4625,13","0,00",05/10/2023,17:40
4,0000000000019255728,000001/24,Realizada,NÃO,Sem informação,52000,Ministério da Defesa,52121,Comando do Exército,NaN,...,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,"4625,13","0,00",05/10/2023,17:34

In [42]:
# Garante que os nomes das colunas não tenham espaços extras
trecho_df.columns = trecho_df.columns.str.strip()
aereas_realizadas.columns = aereas_realizadas.columns.str.strip()

# pega o dataframe trecho_df e filtra pelos identificadores de viagem que estão em aereas_realizadas
aereas_filtradas = trecho_df[trecho_df['Identificador do processo de viagem'].isin(aereas_realizadas['Identificador do processo de viagem'])]

In [43]:
aereas_filtradas.describe()

,Identificador do processo de viagem,Número da Proposta (PCDP),Sequência Trecho,Origem - Data,Origem - País,Origem - UF,Origem - Cidade,Destino - Data,Destino - País,Destino - UF,Destino - Cidade,Meio de transporte,Número Diárias,Missao?
count,534650,534650,534650,534650,534650,515472,534650,534650,534650,515677,534650,534650,534650,534650
unique,212102,55924,57,417,165,28,3417,425,166,28,3417,8,298,2
top,0000000000019673146,Sem informaçã,1,08/11/2024,Brasil,Distrito Federal,Brasília,29/11/2024,Brasil,Distrito Federal,Brasília,Aéreo,"0,00",Não
freq,57,1717,212102,3641,515462,121971,121971,6051,515667,122934,122934,406147,169737,288231

In [44]:
aereas_realizadas.head()

,Identificador do processo de viagem,Número da Proposta (PCDP)_x,Situação,Viagem Urgente,Justificativa Urgência Viagem,Código do órgão superior,Nome do órgão superior,Código órgão solicitante,Nome órgão solicitante,CPF viajante,...,País - Origem volta,UF - Origem volta,Cidade - Origem volta,Pais - Destino volta,UF - Destino volta,Cidade - Destino volta,Valor da passagem,Taxa de serviço,Data da emissão/compra,Hora da emissão/compra
0,0000000000019177818,000001/24-1C,Realizada,SIM,Inclusão das diárias.,26000,Ministério da Educação,26271,Fundação Universidade de Brasília,***.626.601-**,...,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,"6871,34","6,60",19/09/2023,18:53
1,0000000000019177818,000001/24-1C,Realizada,SIM,Inclusão das diárias.,26000,Ministério da Educação,26271,Fundação Universidade de Brasília,***.626.601-**,...,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,"7,77","6,60",19/09/2023,18:53
2,0000000000019220977,000001/24-1C,Realizada,NÃO,Sem informação,26000,Ministério da Educação,26258,Universidade Tecnológica Federal do Paraná,***.133.960-**,...,Portugal,NaN,Porto,Brasil,Paraná,Curitiba,"8596,69","0,00",31/08/2023,14:49
3,0000000000019255612,000002/24,Realizada,NÃO,Sem informação,52000,Ministério da Defesa,52121,Comando do Exército,***.480.087-**,...,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,"4625,13","0,00",05/10/2023,17:40
4,0000000000019255728,000001/24,Realizada,NÃO,Sem informação,52000,Ministério da Defesa,52121,Comando do Exército,NaN,...,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,Sem informação,"4625,13","0,00",05/10/2023,17:34

In [ ]:
origens = aereas['Origem - Cidade']
destinos = aereas['Destino - Cidade']
#converter para dataframe
origens = pd.DataFrame(origens)
destinos = pd.DataFrame(destinos)
origens.describe()

       Origem - Cidade
count             9434
unique             931
top           Brasília
freq               363

In [ ]:
destinos.describe()

       Destino - Cidade
count              9434
unique              938
top            Brasília
freq                369

In [ ]:
origens.dropna(inplace=True)
destinos.dropna(inplace=True)
print(origens)
print(destinos)

         Origem - Cidade
2              São Paulo
3             Uberlândia
52         Foz do Iguaçu
66             São Paulo
69              Brasília
...                  ...
1702085  Nova Petrópolis
1702986         Brasília
1702987         Inválido
1703374        São Paulo
1703375         Inválido

[9434 rows x 1 columns]
        Destino - Cidade
2             Uberlândia
3              São Paulo
52              Brasília
66              Brasília
69             São Paulo
...                  ...
1702085     Porto Alegre
1702986         Inválido
1702987         Brasília
1703374         Inválido
1703375        São Paulo

[9434 rows x 1 columns]

In [ ]:
from distanciaCidades import Distancia

# for origem, destino in zip(origens, destinos):
#    resultado = calcular_distancia.calcular(origem, destino)
# i = 0

resultados = []
for i in range(10):
    origem_cidade = origens.iloc[i]['Origem - Cidade']
    destino_cidade = destinos.iloc[i]['Destino - Cidade']
    resultado = calcular_distancia.calcular(origem_cidade, destino_cidade)
    resultados.append(resultado)
print(resultados)

[{'origem': {'latitude': -23.5506507, 'longitude': -46.6333824, 'nome': 'São Paulo'}, 'destino': {'latitude': -18.9188041, 'longitude': -48.2767837, 'nome': 'Uberlândia'}, 'distancia_km': 542.4512288291022, 'mapa_url': 'https://www.google.com/maps/dir/-23.5506507,-46.6333824/-18.9188041,-48.2767837'}, {'origem': {'latitude': -18.9188041, 'longitude': -48.2767837, 'nome': 'Uberlândia'}, 'destino': {'latitude': -23.5506507, 'longitude': -46.6333824, 'nome': 'São Paulo'}, 'distancia_km': 542.4512288291022, 'mapa_url': 'https://www.google.com/maps/dir/-18.9188041,-48.2767837/-23.5506507,-46.6333824'}, {'origem': {'latitude': -25.5304023, 'longitude': -54.5830692, 'nome': 'Foz do Iguaçu'}, 'destino': {'latitude': -10.3333333, 'longitude': -53.2, 'nome': 'Brasil'}, 'distancia_km': 1696.1111421878663, 'mapa_url': 'https://www.google.com/maps/dir/-25.5304023,-54.5830692/-10.3333333,-53.2'}, {'origem': {'latitude': -23.5506507, 'longitude': -46.6333824, 'nome': 'São Paulo'}, 'destino': {'latitude': -10.3333333, 'longitude': -53.2, 'nome': 'Brasil'}, 'distancia_km': 1626.3698693093886, 'mapa_url': 'https://www.google.com/maps/dir/-23.5506507,-46.6333824/-10.3333333,-53.2'}, {'origem': {'latitude': -10.3333333, 'longitude': -53.2, 'nome': 'Brasil'}, 'destino': {'latitude': -23.5506507, 'longitude': -46.6333824, 'nome': 'São Paulo'}, 'distancia_km': 1626.3698693093886, 'mapa_url': 'https://www.google.com/maps/dir/-10.3333333,-53.2/-23.5506507,-46.6333824'}, {'origem': {'latitude': -28.6237365, 'longitude': -49.0288664, 'nome': 'Jaguaruna'}, 'destino': {'latitude': -10.3333333, 'longitude': -53.2, 'nome': 'Brasil'}, 'distancia_km': 2079.733452457861, 'mapa_url': 'https://www.google.com/maps/dir/-28.6237365,-49.0288664/-10.3333333,-53.2'}, {'origem': {'latitude': -10.3333333, 'longitude': -53.2, 'nome': 'Brasil'}, 'destino': {'latitude': -28.6237365, 'longitude': -49.0288664, 'nome': 'Jaguaruna'}, 'distancia_km': 2079.733452457861, 'mapa_url': 'https://www.google.com/maps/dir/-10.3333333,-53.2/-28.6237365,-49.0288664'}, {'origem': {'latitude': 13.8000382, 'longitude': -88.9140683, 'nome': 'El Salvador'}, 'destino': {'latitude': -27.5973002, 'longitude': -48.5496098, 'nome': 'Florianópolis'}, 'distancia_km': 6333.414425583125, 'mapa_url': 'https://www.google.com/maps/dir/13.8000382,-88.9140683/-27.5973002,-48.5496098'}, {'origem': {'latitude': -27.5973002, 'longitude': -48.5496098, 'nome': 'Florianópolis'}, 'destino': {'latitude': 13.8000382, 'longitude': -88.9140683, 'nome': 'El Salvador'}, 'distancia_km': 6333.414425583125, 'mapa_url': 'https://www.google.com/maps/dir/-27.5973002,-48.5496098/13.8000382,-88.9140683'}, {'origem': {'latitude': -25.4295963, 'longitude': -49.2712724, 'nome': 'Curitiba'}, 'destino': {'latitude': -8.0584933, 'longitude': -34.8848193, 'nome': 'Recife'}, 'distancia_km': 2460.417911468566, 'mapa_url': 'https://www.google.com/maps/dir/-25.4295963,-49.2712724/-8.0584933,-34.8848193'}]

In [ ]:
import pandas as pd
from distanciaCidades import Distancia

# Inicializa a classe
calcular_distancia = Distancia()

# Lista para armazenar resultados estruturados
dados = []

# Itera pelas 10 primeiras linhas (ou até onde houver dados)
for i in range(min(10, len(origens), len(destinos))):
    origem_cidade = origens.iloc[i]['Origem - Cidade']
    destino_cidade = destinos.iloc[i]['Destino - Cidade']
    
    resultado = calcular_distancia.calcular(origem_cidade, destino_cidade)
    
    if resultado:
        dados.append({
            'id': i,
            'origem': resultado['origem']['nome'],
            'destino': resultado['destino']['nome'],
            'distancia': round(resultado['distancia_km'], 2)
        })
    else:
        dados.append({
            'id': i,
            'origem': origem_cidade,
            'destino': destino_cidade,
            'distancia': None
        })

# Criação do DataFrame final
df_distancia = pd.DataFrame(dados)

# Exibe resultado
print(df_distancia)

   id      origem     destino  distancia
0   0  Rio Branco      Xapuri     105.62
1   1      Xapuri  Rio Branco     105.62
2   2   São Paulo  Uberlândia     542.45
3   3  Uberlândia   São Paulo     542.45
4   4   São Paulo  Uberlândia     542.45
5   5  Uberlândia   São Paulo     542.45
6   6   São Paulo  Uberlândia     542.45
7   7  Uberlândia   São Paulo     542.45
8   8       Paris      Brasil    8520.26
9   9       Paris       Lille     204.76

In [ ]:
# resultado = pd.DataFrame(resultado, columns=['Origem', 'Destino', 'Distância'])
# df_distancia.describe()
print(df_distancia)

   id      origem     destino  distancia
0   0  Rio Branco      Xapuri     105.62
1   1      Xapuri  Rio Branco     105.62
2   2   São Paulo  Uberlândia     542.45
3   3  Uberlândia   São Paulo     542.45
4   4   São Paulo  Uberlândia     542.45
5   5  Uberlândia   São Paulo     542.45
6   6   São Paulo  Uberlândia     542.45
7   7  Uberlândia   São Paulo     542.45
8   8       Paris      Brasil    8520.26
9   9       Paris       Lille     204.76

In [ ]:
from pprint import pprint

pprint(resultado)
# Exibe as primeiras linhas do DataFrame de origens e destinos
print(origens.head())
print(destinos.head())

{'destino': {'latitude': 59.9606739,
             'longitude': 30.1586551,
             'nome': 'Санкт-Петербург'},
 'distancia_km': 10634.983626241788,
 'mapa_url': 'https://www.google.com/maps/dir/-10.3333333,-53.2/59.9606739,30.1586551',
 'origem': {'latitude': -10.3333333, 'longitude': -53.2, 'nome': 'Brasil'}}
  Origem - Cidade
0      Rio Branco
1          Xapuri
2       São Paulo
3      Uberlândia
4       São Paulo
  Destino - Cidade
0           Xapuri
1       Rio Branco
2       Uberlândia
3        São Paulo
4       Uberlândia