In [ ]:
https://portaldatransparencia.gov.br/download-de-dados/despesas-execucao/202501

In [11]:
from despesas import Despesas
import pandas as pd
import numpy as np
# Cria uma instância da classe Despesas para o ano de 2025 e mês de janeiro
#e salva como dataframe

# Obs: O ano e mês podem ser alterados conforme necessário


desp = Despesas(2025, 1)
despesas = desp.pegarDespesas()
# Converte o dicionário de DataFrames em um único DataFrame
despesas = pd.concat(despesas.values(), ignore_index=True)

🔄 Fazendo download de: https://portaldatransparencia.gov.br/download-de-dados/despesas-execucao/202501
✅ Arquivo ZIP salvo em: dadosDespesas/despesas_202501.zip
✅ Arquivos extraídos para: d:\projetoExtensao\despesas\dadosDespesas\dados_despesas_202501
📁 Conteúdo extraído:
 - 202501_Despesas.csv
✅ Arquivo ZIP removido: dadosDespesas/despesas_202501.zip
✅ 202501_Despesas.csv carregado com 48911 linhas.

In [12]:

despesas.describe()  # Exibe a descrição estatística dos DataFrames

,Ano e mês do lançamento,Código Órgão Superior,Nome Órgão Superior,Código Órgão Subordinado,Nome Órgão Subordinado,Código Unidade Gestora,Nome Unidade Gestora,Código Gestão,Nome Gestão,Código Unidade Orçamentária,...,Código Elemento de Despesa,Nome Elemento de Despesa,Código Modalidade da Despesa,Modalidade da Despesa,Valor Empenhado (R$),Valor Liquidado (R$),Valor Pago (R$),Valor Restos a Pagar Inscritos (R$),Valor Restos a Pagar Cancelado (R$),Valor Restos a Pagar Pagos (R$)
count,48911,48911,48911,48911,48372,48911,48911,48710,48710,48911,...,48911,48911,48911,48911,48911,48911,48911,48911,48911,48911
unique,1,36,36,250,249,3005,2623,186,186,355,...,66,66,12,12,18303,13081,7082,695,1607,31719
top,2025/01,26000,Ministério da Educação,52121,Comando do Exército,257001,COMPANHIA DE PESQUISA DE RECURSOS MINERAIS,00001,TESOURO NACIONAL,52121,...,39,Outros Serviços de Terceiros - Pessoa Juríd,90,Aplicações Diretas,"0,00","0,00","0,00","0,00","0,00","0,00"
freq,48911,16231,16231,4718,4718,640,676,22791,22791,4209,...,9959,9959,45062,45062,22800,34555,40990,48197,47127,14439

In [13]:
despesas.head()  # Exibe as primeiras linhas do DataFrame

,Ano e mês do lançamento,Código Órgão Superior,Nome Órgão Superior,Código Órgão Subordinado,Nome Órgão Subordinado,Código Unidade Gestora,Nome Unidade Gestora,Código Gestão,Nome Gestão,Código Unidade Orçamentária,...,Código Elemento de Despesa,Nome Elemento de Despesa,Código Modalidade da Despesa,Modalidade da Despesa,Valor Empenhado (R$),Valor Liquidado (R$),Valor Pago (R$),Valor Restos a Pagar Inscritos (R$),Valor Restos a Pagar Cancelado (R$),Valor Restos a Pagar Pagos (R$)
0,2025/01,26000,Ministério da Educação,26418,"Instituto Federal de Educação, Ciência e Tecno...",155171,IFPE - CAMPUS PALMARES,26418,"INST.FED.DE EDUC.,CIENC.E TEC.DE PERNAMBUCO",26298,...,48,Outros Auxílios Financeiros a Pessoas Físic,90,Aplicações Diretas,"0,00","0,00","0,00","0,00","0,00","7674,00"
1,2025/01,22000,Ministério da Agricultura e Pecuária,22000,Ministério da Agricultura e Pecuária - Unidade...,130080,SUPERINT.DE AGRICULTURA E PECUARIA - SFA/GO,00001,TESOURO NACIONAL,22101,...,39,Outros Serviços de Terceiros - Pessoa Juríd,90,Aplicações Diretas,"7625,00","0,00","0,00","0,00","0,00","138,92"
2,2025/01,49000,Ministério do Desenvolvimento Agrário e Agr,22211,Companhia Nacional de Abastecimento,135100,COMPANHIA NACIONAL DE ABASTECIMENTO,22211,COMPANHIA NACIONAL DE ABASTECIMENTO,49202,...,40,Serviços de Tecnologia da Informação e Com,90,Aplicações Diretas,"14244,05","14244,05","12730,03","0,00","0,00","152213,92"
3,2025/01,26000,Ministério da Educação,26246,Universidade Federal de Santa Catarina,153163,UNIVERSIDADE FEDERAL DE SANTA CATARINA,15237,UNIVERSIDADE FEDERAL DE SANTA CATARINA,26246,...,18,Auxílio Financeiro a Estudantes,90,Aplicações Diretas,"91992,00","0,00","0,00","0,00","0,00","3085,65"
4,2025/01,32000,Ministério de Minas e Energia,32000,Ministério de Minas e Energia - Unidades com v...,320084,SUBSECRETARIA DE TECNOLOGIA E INOVACAO/MME,00001,TESOURO NACIONAL,32101,...,40,Serviços de Tecnologia da Informação e Com,90,Aplicações Diretas,"58895,51","34723,33","22370,00","0,00","0,00","252720,49"